version: 2
build:
  os: ubuntu-24.04
  jobs:
    post_checkout:
      # unshallow so the version works
      - git fetch --unshallow
    pre_install:
        # see https://github.com/readthedocs/readthedocs.org/issues/8201
      - git update-index --assume-unchanged docs/source/conf.py
      # editable install with the docs dependency-group
      - python -m pip install -e . --group docs
  tools:
    python: "3.13"
sphinx:
  configuration: docs/source/conf.py
